version: '3'
services:
  app:
    image: node:18-alpine
    ports:
      - '80:5173'
    working_dir: /app
    command: sh -c "npm rebuild esbuild && npm run dev"
    volumes:
      - .:/app
    networks:
      - stock-net
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - 5432:5432
    networks:
      - stock-net
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
networks:
  stock-net:
